import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)))
const tokens = JSON.parse(readFileSync(path.join(root, 'design/tokens.json'), 'utf8'))

const refPattern = /^\{(.+)\}$/

function primitiveLookup(colorTokens) {
  const map = new Map()
  for (const token of colorTokens) {
    if (typeof token.value === 'string') map.set(token.name, token.value)
  }
  return map
}

function resolve(value, primitives) {
  const match = refPattern.exec(value)
  if (!match) return value
  const resolved = primitives.get(match[1])
  if (!resolved) throw new Error(`Unknown token reference: ${value}`)
  return resolved
}

function buildColors(colorTokens) {
  const primitives = primitiveLookup(colorTokens)
  const rootLines = []
  const darkLines = []

  for (const token of colorTokens) {
    if (typeof token.value === 'string') {
      rootLines.push(`  --${token.name}: ${token.value};`)
      continue
    }
    const light = resolve(token.value.light, primitives)
    const dark = resolve(token.value.dark, primitives)
    rootLines.push(`  --${token.name}: ${light};`)
    darkLines.push(`  --${token.name}: ${dark};`)
  }

  return { rootLines, darkLines }
}

function buildShadows(shadowTokens) {
  const rootLines = []
  const darkLines = []
  for (const token of shadowTokens) {
    const varName = token.name === 'glow' ? 'shadow-glow' : token.name
    rootLines.push(`  --raw-${varName}: ${token.value.light};`)
    darkLines.push(`  --raw-${varName}: ${token.value.dark};`)
  }
  return { rootLines, darkLines }
}

function buildSimple(tokenList, prefix = '') {
  return tokenList.map((token) => `  --${prefix}${token.name}: ${token.value};`)
}

function buildTypography(typeSection) {
  const lines = []
  for (const [role, family] of Object.entries(typeSection.families)) {
    lines.push(`  --raw-font-${role}: ${family};`)
  }
  for (const group of typeSection.groups) {
    for (const style of group.styles) {
      lines.push(`  --text-${style.name}-size: ${style.fontSize};`)
      lines.push(`  --text-${style.name}-line: ${style.lineHeight};`)
      lines.push(`  --text-${style.name}-weight: ${style.fontWeight};`)
      if (style.letterSpacing) lines.push(`  --text-${style.name}-tracking: ${style.letterSpacing};`)
    }
  }
  return lines
}

const { rootLines: colorRoot, darkLines: colorDark } = buildColors(tokens.color.tokens)
const { rootLines: shadowRoot, darkLines: shadowDark } = buildShadows(tokens.shadow.tokens)
const typographyLines = buildTypography(tokens.type)
const spacingLines = buildSimple(tokens.spacing.tokens)
const radiusLines = buildSimple(tokens.radius.tokens, 'raw-')

const output = `/* Generated by scripts/build-tokens.mjs from design/tokens.json — do not edit by hand. */
:root {
${colorRoot.join('\n')}
${shadowRoot.join('\n')}
${typographyLines.join('\n')}
${spacingLines.join('\n')}
${radiusLines.join('\n')}
}

:root[data-theme='dark'] {
${colorDark.join('\n')}
${shadowDark.join('\n')}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']):not([data-theme='dark']) {
${colorDark.join('\n')}
${shadowDark.join('\n')}
  }
}
`

mkdirSync(path.join(root, 'src/styles'), { recursive: true })
writeFileSync(path.join(root, 'src/styles/tokens.css'), output)
console.log('Wrote src/styles/tokens.css')
